

---
name: Upgrade Tag Version

on:
  pull_request:
    types: [merged]

jobs:
  upgrade-tag-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Upgrade Tag Version
      run: |
        echo "Upgrading tag version for Git..."

        # Get the current tag version
        current_version=$(git describe --tags)

        # Split the version string into an array of version components
        IFS='.' read -a version_components <<< "$current_version"

        # Increment the patch version component
        version_components[2]=$((${version_components[2]} + 1))

        # Join the version components back into a string
        new_version="${version_components[0]}.${version_components[1]}.${version_components[2]}"

        # Create a new tag with the upgraded version
        git tag $new_version

        # Push the new tag to the remote repository
        git push origin $new_version

        echo "Tag version upgraded to $new_version."
